## 라이브러리 불러오기
- 라이브러리 불러오고, 버전 확인


In [ ]:
# 약어 사용

import numpy as np
print(np.__version__)

1.21.6


In [ ]:
# 약어 미사용

import numpy
print(numpy.__version__)

1.21.6


## NumPy 배열로 변환
- 수치 연산을 하고 싶다!
- 파이썬 기초 자료형을 배열로 변환한다.
  - 형변환 개념과 유사..
  

In [ ]:
temp = [1,2,3,4,5,6,7,8,9]
result = np.array(temp)

print(type(result))
print(result)

# result.argsort()
# result.max()

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


### 배열의 크기 확인
- 배열은 1차원 / 2차원 / 3차원 이냐 중요함!

In [ ]:
print(result.shape) # 몇 행 몇 열 이냐
print(result.ndim) # 몇차원이냐

(9,)
1


### 다차원 배열 만들기

In [ ]:
temp = np.array([[2,4,6], [8,10,12]])
print(temp)
print(temp.shape)
print(temp.ndim)


[[ 2  4  6]
 [ 8 10 12]]
(2, 3)
2


- 3차원 배열도 가능
- 4차원 배열도 가능 ...


## 여러 배열 생성 기본 함수
- np.arange()


In [ ]:
temp = np.arange(5)
print(temp)

[0 1 2 3 4]


In [ ]:
temp_z = np.zeros((2, 2, 2))
print(temp_z)
print(temp_z.shape)
print(temp_z.ndim)

# 데이터 타입

print(temp_z.dtype)
# 기본값은 64

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
(2, 2, 2)
3
float64


### 데이터 타입 크기 지정
- dtype = '원하는 타입 크기 지정'

In [ ]:
temp_one = np.ones((3, 4), dtype = 'int32')
print(temp_one)
print(temp_one.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


### reshape
- 배열의 차원을 바꿀 수 있다
- ```-1```은 자동...?

In [ ]:
result = temp_one.reshape(2, 6)
print(result)
print(result.shape)


result = temp_one.reshape(2, 2, 3)

print(result)
print(result.shape)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]
(2, 6)
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


## 인덱싱 슬라이싱


In [ ]:
temp = np.arange(0, 4)
print(temp)

[0 1 2 3]


In [ ]:
temp[0:2]

array([0, 1])

In [ ]:
temp = np.arange(3, 30, 3).reshape(3, 3)
temp

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [ ]:
temp[0:2, 0:3]


array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
temp[1:3, :]

array([[12, 15, 18],
       [21, 24, 27]])

In [ ]:
temp[:, 1:3]

array([[ 6,  9],
       [15, 18],
       [24, 27]])

In [ ]:
temp = np.arange(2, 30, 2) # (몇부터, 어디바로직전까지, 얼마씩)
print(temp)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## 난수 생성
- 임의의 숫자를 생성


In [ ]:
from numpy import random  # random클래스
x = random.rand()
print(x)

# 위에 있는 코드랑 다른 방법.. 같은 의미임.
# import numpy
# x = numpy.random.rand()
# print(x)

0.9081965671819472


- 임의의 정수


In [ ]:
from numpy import random

#  

x = random.randint(100, size = (5))
# x = random.randint(100, size = (5, 2))      # 2차원
# x = random.randint(100, size = (5, 2, 3))   # 3차원

print(x)

[ 9 36 56 60 17]


## 배열 연산


In [ ]:
array01 = random.randint(100, size = (5))
array02 = random.randint(1000, size = (5))

print(array01)
print(array02)


[62 13 95 84 60]
[252 662 865 396 194]


In [ ]:
# 덧셈

np.add(array01, array02)

array([314, 675, 960, 480, 254])

In [ ]:
# 뺄셈

np.subtract(array01, array02)

array([-190, -649, -770, -312, -134])

In [ ]:
# 곱셈

np.multiply(array01, array02)

array([15624,  8606, 82175, 33264, 11640])

In [ ]:
# 나눗셈

np.divide(array01, array02)

array([0.24603175, 0.01963746, 0.10982659, 0.21212121, 0.30927835])

## 소수점 제거


In [ ]:
array01 = np.trunc([-1.23, 1,23])
array01

array([-1.,  1., 23.])

In [ ]:
array01 = np.round([-1.2312312322, 1,2344632341], 3)
array01

array([-1.23100000e+00,  1.00000000e+00,  2.34463234e+09])

In [ ]:
array01 = np.floor([-1.2312312322, 1,2344632341])
array01

array([-2.00000000e+00,  1.00000000e+00,  2.34463234e+09])

In [ ]:
array01 = np.ceil([-1.2312312322, 1,2344632341])
array01

array([-1.00000000e+00,  1.00000000e+00,  2.34463234e+09])

## NumPy 조건식
- numpy.select() : 다중 조건문
- numpy.where() : 단일 조건문


In [ ]:
array01 = np.arange(10)
array01

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 배열에서 5미만이면, 원래 값 반환,
# 그 외에는 원래 값 * 100

import numpy as np

#           조건식      참          거짓
np.where(array01 < 5, array01, array01 * 100)


array([  0,   1,   2,   3,   4, 500, 600, 700, 800, 900])

- 다중조건문


In [ ]:
# 배열에서 3미만이면, 원래 값 +10 반환,
# 7이상이면 원래 값 * 100
# 그 외에는 원래 값

# np.select(조건리스트, 결과리스트, default 값)

cond_list = [array01 < 3, array01 >= 7]
result_list = [array01 + 10, array01 * 100]
np.select(cond_list, result_list, default = array01)

array([ 10,  11,  12,   3,   4,   5,   6, 700, 800, 900])

## Pandas 판다스

In [ ]:
import pandas as pd
print(pd.__version__)

1.3.5


- 버전 차이가 있다.
- 새로 생긴 함수가 있는 반면, 없어지는 함수도 존재..
  - deprecated warning. message 출력됨.
  

In [ ]:
d = {"a":1, "b":2}
ser = pd.Series(data = d, index = ["a", "b"])
ser

a    1
b    2
dtype: int64

In [ ]:
print(type(ser))

<class 'pandas.core.series.Series'>


In [ ]:
d = {"col1" : [1, 2], "col2" : [3, 4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
result = df["col1"]
print(result)
print(type(result))

0    1
1    2
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
result = df[["col1"]]
print(result)
print(type(result))

   col1
0     1
1     2
<class 'pandas.core.frame.DataFrame'>


## 구글 드라이브 연동


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/2023/human/'
# data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/2023/human/Lemonade2016.csv')

data = pd.read_csv(DATA_PATH + 'Lemonade2016.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         31 non-null     object 
 1   Location     32 non-null     object 
 2   Lemon        32 non-null     int64  
 3   Orange       32 non-null     int64  
 4   Temperature  32 non-null     int64  
 5   Leaflets     31 non-null     float64
 6   Price        32 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.9+ KB


- 데이터 요약
 - 기초통계량 : 평균, 사분위수(상위n%, etc..), 표준편차(==> 회귀 설명)

In [ ]:
data.describe()

# data['Lemon'].describe()

Lemon      Orange  Temperature    Leaflets      Price
count   32.000000   32.000000    32.000000   31.000000  32.000000
mean   116.156250   80.000000    78.968750  108.548387   0.354688
std     25.823357   21.863211     4.067847   20.117718   0.113137
min     71.000000   42.000000    70.000000   68.000000   0.250000
25%     98.000000   66.750000    77.000000   90.000000   0.250000
50%    113.500000   76.500000    80.500000  108.000000   0.350000
75%    131.750000   95.000000    82.000000  124.000000   0.500000
max    176.000000  129.000000    84.000000  158.000000   0.500000

In [ ]:
data['Location']

0      Park
1      Park
2      Park
3     Beach
4     Beach
5     Beach
6     Beach
7     Beach
8     Beach
9     Beach
10    Beach
11    Beach
12    Beach
13    Beach
14    Beach
15    Beach
16    Beach
17    Beach
18     Park
19     Park
20     Park
21     Park
22     Park
23     Park
24     Park
25     Park
26     Park
27     Park
28     Park
29     Park
30    Beach
31    Beach
Name: Location, dtype: object

In [ ]:
# 각 value(park, beach) 숫자 세기

data['Location'].value_counts()

Beach    17
Park     15
Name: Location, dtype: int64

## 새로운 컬럼 추가
- 오렌지와 레몬 판매량 합계 구하기


In [ ]:
data["판매량"] = data["Lemon"] + data["Orange"]
print(data)
print("=================================================================================")

data.head()

         Date Location  Lemon  Orange  Temperature  Leaflets  Price  판매량
0    7/1/2016     Park     97      67           70      90.0   0.25  164
1    7/2/2016     Park     98      67           72      90.0   0.25  165
2    7/3/2016     Park    110      77           71     104.0   0.25  187
3    7/4/2016    Beach    134      99           76      98.0   0.25  233
4    7/5/2016    Beach    159     118           78     135.0   0.25  277
5    7/6/2016    Beach    103      69           82      90.0   0.25  172
6    7/6/2016    Beach    103      69           82      90.0   0.25  172
7    7/7/2016    Beach    143     101           81     135.0   0.25  244
8         NaN    Beach    123      86           82     113.0   0.25  209
9    7/9/2016    Beach    134      95           80     126.0   0.25  229
10  7/10/2016    Beach    140      98           82     131.0   0.25  238
11  7/11/2016    Beach    162     120           83     135.0   0.25  282
12  7/12/2016    Beach    130      95           84 

Date Location  Lemon  Orange  Temperature  Leaflets  Price  판매량
0  7/1/2016     Park     97      67           70      90.0   0.25  164
1  7/2/2016     Park     98      67           72      90.0   0.25  165
2  7/3/2016     Park    110      77           71     104.0   0.25  187
3  7/4/2016    Beach    134      99           76      98.0   0.25  233
4  7/5/2016    Beach    159     118           78     135.0   0.25  277

In [ ]:
# 매출액 구하기

data["매출액"] = data["Price"] * data["판매량"]
print(data.head())

       Date Location  Lemon  Orange  Temperature  Leaflets  Price  판매량    매출액
0  7/1/2016     Park     97      67           70      90.0   0.25  164  41.00
1  7/2/2016     Park     98      67           72      90.0   0.25  165  41.25
2  7/3/2016     Park    110      77           71     104.0   0.25  187  46.75
3  7/4/2016    Beach    134      99           76      98.0   0.25  233  58.25
4  7/5/2016    Beach    159     118           78     135.0   0.25  277  69.25


## 데이터 내보내기
- 함수를 찾아야 함.
  - pandas 문서, 구글링 등
- csv 파일 내보내기
  - 결과.csv
- 엑셀로 내보내기
 - 결과.xlsx


In [ ]:
# .csv 파일

data.to_csv('/content/drive/MyDrive/Colab Notebooks/2023/human/결과.csv')

In [ ]:
# .xlsx 파일

data.to_excel('/content/drive/MyDrive/Colab Notebooks/2023/human/결과.xlsx')

## 컬럼 삭제
- 컬럼을 삭제한다.

In [ ]:
# data

# 열을 지운 것
data2 = data.drop('매출액', axis = 1)
data2.head(3)

# data2 = data.drop(['매출액', '판매량'], axis = 1)
# data2.head(3)

Date Location  Lemon  Orange  Temperature  Leaflets  Price  판매량
0  7/1/2016     Park     97      67           70      90.0   0.25  164
1  7/2/2016     Park     98      67           72      90.0   0.25  165
2  7/3/2016     Park    110      77           71     104.0   0.25  187

In [ ]:
# 행을 지우는 것

data2 = data.drop(10, axis = 0)
data2.head(11)

Date Location  Lemon  Orange  Temperature  Leaflets  Price  판매량  \
0    7/1/2016     Park     97      67           70      90.0   0.25  164   
1    7/2/2016     Park     98      67           72      90.0   0.25  165   
2    7/3/2016     Park    110      77           71     104.0   0.25  187   
3    7/4/2016    Beach    134      99           76      98.0   0.25  233   
4    7/5/2016    Beach    159     118           78     135.0   0.25  277   
5    7/6/2016    Beach    103      69           82      90.0   0.25  172   
6    7/6/2016    Beach    103      69           82      90.0   0.25  172   
7    7/7/2016    Beach    143     101           81     135.0   0.25  244   
8         NaN    Beach    123      86           82     113.0   0.25  209   
9    7/9/2016    Beach    134      95           80     126.0   0.25  229   
11  7/11/2016    Beach    162     120           83     135.0   0.25  282   

      매출액  
0   41.00  
1   41.25  
2   46.75  
3   58.25  
4   69.25  
5   43.00  
6   43.00  
7   61.00  
8   52.25  
9   57.25  
11  70.50

In [ ]:
d = {"매출액":1, "b":2}
ser = pd.Series(data = d, index = ["매출액", "b"])
ser.drop('매출액', axis = 0)

b    2
dtype: int64

In [ ]:
data[0:3]

Date Location  Lemon  Orange  Temperature  Leaflets  Price  판매량    매출액
0  7/1/2016     Park     97      67           70      90.0   0.25  164  41.00
1  7/2/2016     Park     98      67           72      90.0   0.25  165  41.25
2  7/3/2016     Park    110      77           71     104.0   0.25  187  46.75

## SQL 조건절
- 조건식을 통해, 행을 추출
  - 조건식의 True 값만 추출함.
  

In [ ]:
data['판매량'].describe()

count     32.000000
mean     196.156250
std       47.647976
min      113.000000
25%      164.750000
50%      189.000000
75%      226.000000
max      305.000000
Name: 판매량, dtype: float64

In [ ]:
# 판매량이 200이 넘는 데이터만 추출
# 판매량 >= 200

data['판매량'] >= 200

0     False
1     False
2     False
3      True
4      True
5     False
6     False
7      True
8      True
9      True
10     True
11     True
12     True
13    False
14     True
15    False
16    False
17    False
18     True
19     True
20    False
21    False
22    False
23     True
24     True
25     True
26     True
27    False
28    False
29    False
30    False
31    False
Name: 판매량, dtype: bool

In [ ]:
data2 = data[data['판매량'] >= 200]
data2

Date Location  Lemon  Orange  Temperature  Leaflets  Price  판매량  \
3    7/4/2016    Beach    134      99           76      98.0   0.25  233   
4    7/5/2016    Beach    159     118           78     135.0   0.25  277   
7    7/7/2016    Beach    143     101           81     135.0   0.25  244   
8         NaN    Beach    123      86           82     113.0   0.25  209   
9    7/9/2016    Beach    134      95           80     126.0   0.25  229   
10  7/10/2016    Beach    140      98           82     131.0   0.25  238   
11  7/11/2016    Beach    162     120           83     135.0   0.25  282   
12  7/12/2016    Beach    130      95           84      99.0   0.25  225   
14  7/14/2016    Beach    122      85           78     113.0   0.25  207   
18  7/18/2016     Park    131      92           81     122.0   0.50  223   
19  7/19/2016     Park    122      85           78     113.0   0.50  207   
23  7/23/2016     Park    120      82           81     117.0   0.50  202   
24  7/24/2016     Park    121      82           82     117.0   0.50  203   
25  7/25/2016     Park    156     113           84     135.0   0.50  269   
26  7/26/2016     Park    176     129           83     158.0   0.35  305   

       매출액  
3    58.25  
4    69.25  
7    61.00  
8    52.25  
9    57.25  
10   59.50  
11   70.50  
12   56.25  
14   51.75  
18  111.50  
19  103.50  
23  101.00  
24  101.50  
25  134.50  
26  106.75

## iloc loc 속도 비교


In [ ]:
data.head()

Date Location  Lemon  Orange  Temperature  Leaflets  Price  판매량    매출액
0  7/1/2016     Park     97      67           70      90.0   0.25  164  41.00
1  7/2/2016     Park     98      67           72      90.0   0.25  165  41.25
2  7/3/2016     Park    110      77           71     104.0   0.25  187  46.75
3  7/4/2016    Beach    134      99           76      98.0   0.25  233  58.25
4  7/5/2016    Beach    159     118           78     135.0   0.25  277  69.25

In [ ]:
%%time

data.iloc[0:3, 0:2]

CPU times: user 2.44 ms, sys: 0 ns, total: 2.44 ms
Wall time: 2.35 ms


Date Location
0  7/1/2016     Park
1  7/2/2016     Park
2  7/3/2016     Park

In [ ]:
%%time

data.loc[0:2, ['Date', 'Location']]

CPU times: user 1.28 ms, sys: 0 ns, total: 1.28 ms
Wall time: 1.29 ms


Date Location
0  7/1/2016     Park
1  7/2/2016     Park
2  7/3/2016     Park

## Group By
- SQL, R의 Group by와 같음
- 집계함수 (count, sum avg ,,)


In [ ]:
import numpy as np

print(data.groupby('Location')['판매량'].agg([sum, np.mean]))
print("===========================================================================")
data.groupby('Location')[['판매량', '매출액']].agg([sum, np.mean])

           sum        mean
Location                  
Beach     3422  201.294118
Park      2855  190.333333


판매량                 매출액           
           sum        mean     sum       mean
Location                                     
Beach     3422  201.294118  1002.8  58.988235
Park      2855  190.333333  1178.2  78.546667